### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Suzie97** [JeysonFlores/Lightning#1]
Hey there, would like a new app icon for this project?? I can make the icon following the HIG in all sizes.

Thanks for making this app, life savers for me, 👍🏼

**Comment by JeysonFlores** [comment]
The only point I disagree with elementary's HIG is the Iconography, in my opinion flat icons look way better than elementary's cartoonish icons, that's the reason why all my apps use symbolic icons by default. Meaning that the flat-looking icon is made on purpose.

**Comment by Suzie97** [comment]
> The only point I disagree with elementary's HIG is the Iconography, in my opinion flat icons look way better than elementary's cartoonish icons, that's the reason why all my apps use symbolic icons by default. Meaning that the flat-looking icon is made on purpose.

Thank you for the quick response. I respect your opinion. Since, you're not interested, I'll close this issue.
